<?php
require('../assets/fpdf/fpdf.php');
include("../koneksi/koneksi.php");
session_start();
if ($_SESSION['username']=="") {
	header("location:../login/");
}

//$email=$_POST['email'];
$datas=mysql_fetch_array(mysql_query("select * from t4t_wins order by no desc limit 5 "));

class PDF extends FPDF
{

	// Page header
	function Header()
	{
	    // Logo
	    //$this->Image('../img/edited T4T Logo Contest (67).jpg',15,2,60);
	    // Arial bold 15
	    $this->SetFont('Arial','B',18); $this->Ln(10);
	    $this->Cell(0,5,'Tree Allocation',0,1,'C',false);$this->Ln(5);
	    $this->SetFont('Arial','',15);
	    $this->Cell(0,5,' Session Report',0,1,'C',false);
	    //$this->Cell(0,5,'Kota Semarang',0,1,'C',false);

	    // Line break
	    $this->Ln(5);

		$this->SetLineWidth(1);
		$this->Line(10,40,200,40);
		$this->SetLineWidth(0);
		$this->Line(10,41,200,41);
		$this->Ln(3);
		$this->SetFont('Arial','B',13);
	    //$this->Cell(0,10,'Bukti Pembayaran',0,1,'C',false);

	}

	// Page footer
	function Footer()
	{
		date_default_timezone_set('Asia/Jakarta');
		$tanggal=date('d/M/Y - H:i:s');
	    // Position at 1.5 cm from bottom
	    $this->SetY(-15);
	    // Arial italic 8
	    $this->SetFont('Arial','I',8);	    
	    $this->Cell(0,10,'Generated By Yayasan Bumi Hijau Lestari '.$tanggal.'');
	    //$this->cell(0,10,$tanggal);
	    // Page number
	    $this->Cell(0,10,'Page '.$this->PageNo().'/{nb}',0,0,'C');
	}

	// MultiCell Table
	var $widths;
	var $aligns;

	function SetWidths($w)
	{
	    //Set the array of column widths
	    $this->widths=$w;
	}

	function SetAligns($a)
	{
	    //Set the array of column alignments
	    $this->aligns=$a;
	}

	function Row($data)
	{
	    //Calculate the height of the row
	    $nb=0;
	    for($i=0;$i<count($data);$i++)
	        $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
	    $h=5*$nb;
	    //Issue a page break first if needed
	    $this->CheckPageBreak($h);
	    //Draw the cells of the row
	    for($i=0;$i<count($data);$i++)
	    {
	        $w=$this->widths[$i];
	        $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'C';
	        //Save the current position
	        $x=$this->GetX();
	        $y=$this->GetY();
	        //Draw the border
	        $this->Rect($x,$y,$w,$h);
	        //Print the text
	        $this->MultiCell($w,5,$data[$i],0,$a);
	        //Put the position to the right of the cell
	        $this->SetXY($x+$w,$y);
	    }
	    //Go to the next line
	    $this->Ln($h);
	}

	function CheckPageBreak($h)
	{
	    //If the height h would cause an overflow, add a new page immediately
	    if($this->GetY()+$h>$this->PageBreakTrigger)
	        $this->AddPage($this->CurOrientation);
	}

	function NbLines($w,$txt)
	{
	    //Computes the number of lines a MultiCell of width w will take
	    $cw=&$this->CurrentFont['cw'];
	    if($w==0)
	        $w=$this->w-$this->rMargin-$this->x;
	    $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
	    $s=str_replace("\r",'',$txt);
	    $nb=strlen($s);
	    if($nb>0 and $s[$nb-1]=="\n")
	        $nb--;
	    $sep=-1;
	    $i=0;
	    $j=0;
	    $l=0;
	    $nl=1;
	    while($i<$nb)
	    {
	        $c=$s[$i];
	        if($c=="\n")
	        {
	            $i++;
	            $sep=-1;
	            $j=$i;
	            $l=0;
	            $nl++;
	            continue;
	        }
	        if($c==' ')
	            $sep=$i;
	        $l+=$cw[$c];
	        if($l>$wmax)
	        {
	            if($sep==-1)
	            {
	                if($i==$j)
	                    $i++;
	            }
	            else
	                $i=$sep+1;
	            $sep=-1;
	            $j=$i;
	            $l=0;
	            $nl++;
	        }
	        else
	            $i++;
	    }
	    return $nl;
	}
}

$pdf=new PDF('P','mm','A4');
//$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('P');


$pdf->Ln(5);
$pdf->SetFont('Arial','',11);
$pdf->cell(30,7,'Username',0,0,'L');
$pdf->cell(4,7,':',0,0,'L');
$pdf->cell(45,7,$_SESSION['user'],0,0,'L');
$pdf->Ln(7);
$pdf->SetFont('Arial','',11);
$pdf->cell(30,7,'Time Login',0,0,'L');
$pdf->cell(4,7,':',0,0,'L');
$pdf->cell(45,7,$_SESSION['start_login'],0,0,'L');
$pdf->Ln(7);
$pdf->SetFont('Arial','',11);
$pdf->cell(30,7,'Time Logout',0,0,'L');
$pdf->cell(4,7,':',0,0,'L');
$pdf->cell(45,7,$_SESSION['logout'],0,0,'L');
$pdf->Ln(7);


$pdf->Ln(17);

date_default_timezone_set('Asia/Jakarta');
$sekarang=date('d M Y');

// $pdf->Ln(18);
// $pdf->cell(90,0,'',0,0,'C');
// $pdf->cell(110,0,'Semarang, '.$sekarang.'',0,0,'C');
// $pdf->Ln(10);
// $pdf->cell(90,9,'',0,0,'C');
// $pdf->cell(110,9,'Tim Seleksi Calon Karyawan',0,0,'C');


$pdf->SetWidths(array(10,25,30,25,25,15,28,10,10,17));
$jumlah_sesi=$_SESSION['jml_sesi']; 

	$pdf->SetFont('Arial','',8);
	$pdf->SetFillColor(51, 51, 102);
	$pdf->SetTextColor(255, 255, 255);
	$pdf->Cell(10,7,'No',1,0,'C', 1);
	$pdf->Cell(25,7,'Transaction Type',1,0,'C', 1);
	$pdf->Cell(30,7,'Name',1,0,'C', 1);
	$pdf->Cell(25,7,'Order',1,0,'C', 1);
	$pdf->Cell(25,7,'Shipment',1,0,'C', 1);
	$pdf->Cell(15,7,'HTC ID',1,0,'C', 1);
	$pdf->Cell(28,7,'BL',1,0,'C', 1);
	$pdf->Cell(10,7,'Trees',1,0,'C', 1);
	$pdf->Cell(10,7,'WINS',1,0,'C', 1);
	$pdf->Cell(17,7,'1st WINS',1,0,'C', 1);
	$pdf->ln(7);
	
	if ($jumlah_sesi==0) {
		$pdf->SetFillColor(255,255,255);
		$pdf->SetTextColor(0, 0, 0);
		$pdf->Cell(195, 7,  "No Transaction" ,1,0,'C',true );
		$pdf->ln(7);
	}else{
		for ($i=1; $i <= $jumlah_sesi ; $i++) { 
			$jumlah=$i;
			$pdf->SetTextColor(0, 0, 0);
			$pdf->Row(array($i, $_SESSION['type_transaksi'.$jumlah.''],$_SESSION['nama_partisipan'.$jumlah.''],$_SESSION['no_order'.$jumlah.''],$_SESSION['no_shipment'.$jumlah.''],$_SESSION['htc_id'.$jumlah.''],$_SESSION['bl'.$jumlah.''],$_SESSION['qty_trees'.$jumlah.''],$_SESSION['qty_wins'.$jumlah.''],$_SESSION['first_wins'.$jumlah.'']));

		}
	}
	

	$pdf->SetFillColor(51, 51, 102);
	$pdf->SetTextColor(255, 255, 255);
	$pdf->Cell(158,7,'Total',1,0,'C', 1);
	$pdf->Cell(10,7,$_SESSION['tot_pohon'],1,0,'R', 1);
	$pdf->Cell(10,7,$_SESSION['tot_wins'],1,0,'R', 1);
	
	$pdf->ln(7);

	$pdf->SetTextColor(0, 0, 0);
$pdf->Output();
?>